; Assembler file generated by Auto Disassembler V20230623
;                Program developed by Ruud Baltissen
;
; Syntax modified for A09 assembler


D00C1	EQU	$00C1
D00C8	EQU	$00C8
D00D3	EQU	$00D3
D010F	EQU	$010F
A0770	EQU	$0770
D1183	EQU	$1183
P1234	EQU	$1234
D4321	EQU	$4321
D9876	EQU	$9876
 
 
 
        OPT     M09
 


        ORG     $0000				; Begin address of this block
D0000:					;				[0000]
	pshs	b
	adda	,s+
	abx
	adca	#$13
	adca	<$12
	adca	P1234			;				[1234]
	adca	,x
	adca	0,x
	adca	1,x
	adca	-1,x
	adca	15,x
	adca	-16,x
	adca	16,x
	adca	-17,x
	adca	127,x
	adca	-128,x
	adca	$0080,x
	adca	-$0081,x
	adca	a,x
	adca	b,x
	adca	d,x
	adca	,x+
	adca	,x++
	adca	,-x
	adca	,--x
	adca	,y
	adca	0,y
	adca	1,y
	adca	-1,y
	adca	15,y
	adca	-16,y
	adca	16,y
	adca	-17,y
	adca	127,y
	adca	-128,y
	adca	$0080,y
	adca	-$0081,y
	adca	a,y
	adca	b,y
	adca	d,y
	adca	,y+
	adca	,y++
	adca	,-y
	adca	,--y
	adca	[$1234]
	adca	[,s]
	adca	[,u]
	adca	[,x]
	adca	[,--x]
	adca	[,x++]
	adca	[,y]
	adca	[,x]
	adca	[15,x]
	adca	[127,x]
	adca	[$0080,x]
	adca	[a,x]
	adca	[b,x]
	adca	0,x
	adca	1,x
	adca	15,x
	adca	-16,x
	adca	-1,x
	adca	,x+
	adca	,x++
	adca	,-x
	adca	,--x
	adca	,x
	adca	b,x
	adca	a,x
	adca	16,x
	adca	127,x
	adca	-128,x
	adca	-17,x
	adca	$0080,x
	adca	$7FFF,x
	adca	-$8000,x
	adca	-$0081,x
	adca	d,x
	adca	D00C1,pcr
	adca	D00C8,pcr
	adca	D0000,pcr
	adca	D00C8,pcr
	adca	D04A7,pcr
	adca	[$1234]
	adca	[d,x]
	adca	[,s++]
	adca	[,u++]
	adca	[,x++]
	adca	[,y++]
	adca	[,--s]
	adca	[,--u]
	adca	[,--x]
	adca	[,--y]
	adca	[D0000,pcr]
	adca	[D00D3,pcr]
	adca	[D010F,pcr]
	adca	[D0583,pcr]
	adca	,s
	adca	,u
	adca	[D0000,pcr]
	adca	[D0000,pcr]
	adca	[D0000,pcr]
	adca	[D0000,pcr]
	adca	[,--x]
	adca	[,x++]
	adca	,x
	adca	,y
	adca	D0E13,pcr
	adca	[D0E13,pcr]
	adcb	#$13
	adcb	<$12
	adcb	D4321			;				[4321]
	adcb	,x
	adcb	0,x
	adcb	1,x
	adcb	-1,x
	adcb	15,x
	adcb	-16,x
	adcb	16,x
	adcb	-17,x
	adcb	127,x
	adcb	-128,x
	adcb	$0080,x
	adcb	-$0081,x
	adcb	a,x
	adcb	b,x
	adcb	d,x
	adcb	,x+
	adcb	,x++
	adcb	,-x
	adcb	,--x
	adcb	[$1234]
	adcb	[,x]
	adcb	[,x]
	adcb	[15,x]
	adcb	[127,x]
	adcb	[$0080,x]
	adcb	[a,x]
	adcb	[b,x]
	adcb	[d,x]
	adcb	[,s++]
	adcb	[,u++]
	adcb	[,x++]
	adcb	[,y++]
	adcb	[,--s]
	adcb	[,--u]
	adcb	[,--x]
	adcb	[,--y]
	adcb	[D0000,pcr]
	adcb	[D00D3,pcr]
	adcb	[D010F,pcr]
	adcb	[D0583,pcr]
	adcb	,s
	adcb	,u
	adcb	,x
	adcb	,y
	adda	#$13
	adda	<$12
	adda	P1234			;				[1234]
	adda	,x
	adda	0,x
	adda	1,x
	adda	-1,x
	adda	15,x
	adda	-16,x
	adda	16,x
	adda	-17,x
	adda	127,x
	adda	-128,x
	adda	$0080,x
	adda	-$0081,x
	adda	a,x
	adda	b,x
	adda	d,x
	adda	,x+
	adda	,x++
	adda	,-x
	adda	,--x
	adda	[$1234]
	adda	[,x]
	adda	[,x]
	adda	[15,x]
	adda	[127,x]
	adda	[$0080,x]
	adda	[a,x]
	adda	[b,x]
	adda	[d,x]
	adda	[,s++]
	adda	[,u++]
	adda	[,x++]
	adda	[,y++]
	adda	[,--s]
	adda	[,--u]
	adda	[,--x]
	adda	[,--y]
	adda	[D0000,pcr]
	adda	[D00D3,pcr]
	adda	[D010F,pcr]
	adda	[D0583,pcr]
	adda	,s
	adda	,u
	adda	,x
	adda	,y
	addb	#$13
	addb	<$12
	addb	P1234			;				[1234]
	addb	,x
	addb	0,x
	addb	1,x
	addb	-1,x
	addb	15,x
	addb	-16,x
	addb	16,x
	addb	-17,x
	addb	127,x
	addb	-128,x
	addb	$0080,x
	addb	-$0081,x
	addb	a,x
	addb	b,x
	addb	d,x
	addb	,x+
	addb	,x++
	addb	,-x
	addb	,--x
	addb	[$1234]
	addb	[,x]
	addb	[,x]
	addb	[15,x]
	addb	[127,x]
	addb	[$0080,x]
	addb	[a,x]
	addb	[b,x]
	addb	[d,x]
	addb	[,s++]
	addb	[,u++]
	addb	[,x++]
	addb	[,y++]
	addb	[,--s]
	addb	[,--u]
	addb	[,--x]
	addb	[,--y]
	addb	[D0000,pcr]
	addb	[D00D3,pcr]
	addb	[D010F,pcr]
	addb	[D0583,pcr]
	addb	,s
	addb	,u
	addb	,x
	addb	,y
	addd	#$0013			;				[0013]
	addd	<$12
	addd	D9876			;				[9876]
	addd	,x
	addd	0,x
	addd	1,x
	addd	-1,x
	addd	15,x
	addd	-16,x
	addd	16,x
	addd	-17,x
	addd	127,x
	addd	-128,x
	addd	$0080,x
	addd	-$0081,x
	addd	a,x
	addd	b,x
	addd	d,x
	addd	,x+
	addd	,x++
	addd	,-x
	addd	,--x
	addd	[$1234]
	addd	[,x]
	addd	[,x]
	addd	[15,x]
	addd	[127,x]
	addd	[$0080,x]
	addd	[a,x]
	addd	[b,x]
	addd	[d,x]
	addd	[,s++]
	addd	[,u++]
	addd	[,x++]
	addd	[,y++]
	addd	[,--s]
	addd	[,--u]
	addd	[,--x]
	addd	[,--y]
	addd	[D0000,pcr]
	addd	[D00D3,pcr]
	addd	[D010F,pcr]
	addd	[D0583,pcr]
	addd	,s
	addd	,u
	addd	,x
	addd	,y
	anda	#$13
	anda	<$12
	anda	P1234			;				[1234]
	anda	,x
	anda	0,x
	anda	1,x
	anda	-1,x
	anda	15,x
	anda	-16,x
	anda	16,x
	anda	-17,x
	anda	127,x
	anda	-128,x
	anda	$0080,x
	anda	-$0081,x
	anda	a,x
	anda	b,x
	anda	d,x
	anda	,x+
	anda	,x++
	anda	,-x
	anda	,--x
	anda	[$1234]
	anda	[,x]
	anda	[,x]
	anda	[15,x]
	anda	[127,x]
	anda	[$0080,x]
	anda	[a,x]
	anda	[b,x]
	anda	[d,x]
	anda	[,s++]
	anda	[,u++]
	anda	[,x++]
	anda	[,y++]
	anda	[,--s]
	anda	[,--u]
	anda	[,--x]
	anda	[,--y]
	anda	[D0000,pcr]
	anda	[D00D3,pcr]
	anda	[D010F,pcr]
	anda	[D0583,pcr]
	anda	,s
	anda	,u
	anda	,x
	anda	,y
	andb	#$13
	andb	<$12
	andb	P1234			;				[1234]
	andb	,x
	andb	0,x
	andb	1,x
	andb	-1,x
	andb	15,x
	andb	-16,x
	andb	16,x
	andb	-17,x
	andb	127,x
	andb	-128,x
	andb	$0080,x
	andb	-$0081,x
	andb	a,x
	andb	b,x
	andb	d,x
	andb	,x+
	andb	,x++
	andb	,-x
	andb	,--x
	andb	[$1234]
	andb	[,x]
	andb	[,x]
	andb	[15,x]
	andb	[127,x]
	andb	[$0080,x]
	andb	[a,x]
	andb	[b,x]
	andb	[d,x]
	andb	[,s++]
	andb	[,u++]
	andb	[,x++]
	andb	[,y++]
	andb	[,--s]
	andb	[,--u]
	andb	[,--x]
	andb	[,--y]
	andb	[D0000,pcr]
	andb	[D00D3,pcr]
	andb	[D010F,pcr]
	andb	[D0583,pcr]
	andb	,s
	andb	,u
	andb	,x
	andb	,y
	andcc	$74			;				[74]
	andcc	$AA			;				[AA]
	andcc	$55			;				[55]
	asl	<$12
	asl	P1234			;				[1234]
	asl	,x
	asl	0,x
	asl	1,x
	asl	-1,x
	asl	15,x
	asl	-16,x
	asl	16,x
	asl	-17,x
	asl	127,x
	asl	-128,x
	asl	$0080,x
	asl	-$0081,x
	asl	a,x
	asl	b,x
	asl	d,x
	asl	,x+
	asl	,x++
	asl	,-x
	asl	,--x
	asl	[$1234]
	asl	[,x]
	asl	[,x]
	asl	[15,x]
	asl	[127,x]
	asl	[$0080,x]
	asl	[a,x]
	asl	[b,x]
	asl	[d,x]
	asl	[,s++]
	asl	[,u++]
	asl	[,x++]
	asl	[,y++]
	asl	[,--s]
	asl	[,--u]
	asl	[,--x]
	asl	[,--y]
	asl	,s
	asl	,u
	asl	,x
	asl	,y
	asla
	aslb
	asr	<$12
	asr	P1234			;				[1234]
	asr	,x
	asr	0,x
	asr	1,x
	asr	-1,x
	asr	15,x
	asr	-16,x
	asr	16,x
	asr	-17,x
	asr	127,x
	asr	-128,x
	asr	$0080,x
	asr	-$0081,x
	asr	a,x
	asr	b,x
	asr	d,x
	asr	,x+
	asr	,x++
	asr	,-x
	asr	,--x
	asr	[$1234]
	asr	[,x]
	asr	[,x]
	asr	[15,x]
	asr	[127,x]
	asr	[$0080,x]
	asr	[a,x]
	asr	[b,x]
	asr	[d,x]
	asr	[,s++]
	asr	[,u++]
	asr	[,x++]
	asr	[,y++]
	asr	[,--s]
	asr	[,--u]
	asr	[,--x]
	asr	[,--y]
	asr	,s
	asr	,u
	asr	,x
	asr	,y
	asra
	asrb
	bcc	D04A7			;				[04A7]

D04A7:					;				[04A7]
	bcs	D04A7			;				[04A7]

	beq	D04A7			;				[04A7]

	bge	D04A7			;				[04A7]

	bgt	D04A7			;				[04A7]

	bhi	D04A7			;				[04A7]

	bcc	D04A7			;				[04A7]

	bita	#$13
	bita	<$12
	bita	P1234			;				[1234]
	bita	,x
	bita	0,x
	bita	1,x
	bita	-1,x
	bita	15,x
	bita	-16,x
	bita	16,x
	bita	-17,x
	bita	127,x
	bita	-128,x
	bita	$0080,x
	bita	-$0081,x
	bita	a,x
	bita	b,x
	bita	d,x
	bita	,x+
	bita	,x++
	bita	,-x
	bita	,--x
	bita	[$1234]
	bita	[,x]
	bita	[,x]
	bita	[15,x]
	bita	[127,x]
	bita	[$0080,x]
	bita	[a,x]
	bita	[b,x]
	bita	[d,x]
	bita	[,x++]
	bita	[,--x]
	bita	[D0000,pcr]
	bita	[D010F,pcr]
	bita	[D00D3,pcr]
	bita	[D0583,pcr]
	bita	,s
	bita	,u
	bita	,x
	bita	,y
	bitb	#$13
	bitb	<$12
	bitb	P1234			;				[1234]
	bitb	,x
	bitb	0,x
	bitb	1,x
	bitb	-1,x
	bitb	15,x
	bitb	-16,x
	bitb	16,x
	bitb	-17,x
	bitb	127,x
	bitb	-128,x
	bitb	$0080,x
	bitb	-$0081,x
	bitb	a,x
	bitb	b,x
	bitb	d,x
	bitb	,x+
	bitb	,x++
	bitb	,-x
	bitb	,--x
	bitb	[$1234]
	bitb	[,x]
	bitb	[,x]
	bitb	[15,x]
	bitb	[127,x]
	bitb	[$0080,x]
	bitb	[a,x]
	bitb	[b,x]
	bitb	[d,x]
	bitb	[,x++]
	bitb	[,--x]
	bitb	[D0000,pcr]
	bitb	[D010F,pcr]
	bitb	[D00D3,pcr]
	bitb	[D0583,pcr]
	bitb	,s
	bitb	,u
	bitb	,x
	bitb	,y
D0583:					;				[0583]
	ble	D0583			;				[0583]

	bcs	D0583			;				[0583]

	bls	D0583			;				[0583]

	blt	A0593			;				[0593]

	bmi	D0583			;				[0583]

	bne	D0583			;				[0583]

	bpl	D0583			;				[0583]

	bra	D0583			;				[0583]

A0593:					;				[0593]
	brn	D0583			;				[0583]

	bsr	D0583			;				[0583]

	bvc	D0583			;				[0583]

	bvs	D0583			;				[0583]

	pshs	b
	cmpa	,s+
	andcc	$FE			;				[FE]
	andcc	$EF			;				[EF]
	clr	<$12
	clr	P1234			;				[1234]
	clr	,x
	clr	0,x
	clr	1,x
	clr	-1,x
	clr	15,x
	clr	-16,x
	clr	16,x
	clr	-17,x
	clr	127,x
	clr	-128,x
	clr	$0080,x
	clr	-$0081,x
	clr	a,x
	clr	b,x
	clr	d,x
	clr	,x+
	clr	,x++
	clr	,-x
	clr	,--x
	clr	[$1234]
	clr	[,x]
	clr	[,x]
	clr	[15,x]
	clr	[127,x]
	clr	[$0080,x]
	clr	[a,x]
	clr	[b,x]
	clr	[d,x]
	clr	[,x++]
	clr	[,--x]
	clr	,s
	clr	,u
	clr	,x
	clr	,y
	clra
	clrb
	andcc	$FD			;				[FD]
	cmpa	#$13
	cmpa	<$12
	cmpa	P1234			;				[1234]
	cmpa	,x
	cmpa	0,x
	cmpa	1,x
	cmpa	-1,x
	cmpa	15,x
	cmpa	-16,x
	cmpa	16,x
	cmpa	-17,x
	cmpa	127,x
	cmpa	-128,x
	cmpa	$0080,x
	cmpa	-$0081,x
	cmpa	a,x
	cmpa	b,x
	cmpa	d,x
	cmpa	,x+
	cmpa	,x++
	cmpa	,-x
	cmpa	,--x
	cmpa	[$1234]
	cmpa	[,x]
	cmpa	[,x]
	cmpa	[15,x]
	cmpa	[127,x]
	cmpa	[$0080,x]
	cmpa	[a,x]
	cmpa	[b,x]
	cmpa	[d,x]
	cmpa	[,x++]
	cmpa	[,--x]
	cmpa	[D0000,pcr]
	cmpa	[D010F,pcr]
	cmpa	[D00D3,pcr]
	cmpa	[D0583,pcr]
	cmpa	,s
	cmpa	,u
	cmpa	,x
	cmpa	,y
	cmpb	#$13
	cmpb	<$12
	cmpb	P1234			;				[1234]
	cmpb	,x
	cmpb	0,x
	cmpb	1,x
	cmpb	-1,x
	cmpb	15,x
	cmpb	-16,x
	cmpb	16,x
	cmpb	-17,x
	cmpb	127,x
	cmpb	-128,x
	cmpb	$0080,x
	cmpb	-$0081,x
	cmpb	a,x
	cmpb	b,x
	cmpb	d,x
	cmpb	,x+
	cmpb	,x++
	cmpb	,-x
	cmpb	,--x
	cmpb	[$1234]
	cmpb	[,x]
	cmpb	[,x]
	cmpb	[15,x]
	cmpb	[127,x]
	cmpb	[$0080,x]
	cmpb	[a,x]
	cmpb	[b,x]
	cmpb	[d,x]
	cmpb	[,x++]
	cmpb	[,--x]
	cmpb	[D0583,pcr]
	cmpb	,s
	cmpb	,u
	cmpb	,x
	cmpb	,y
	cmpd	#$1234
	cmpd	#$0013
	cmpd	<$12
	cmpd	P1234			;				[1234]
	cmpd	,x
D06D6:					;				[06D6]
	cmpd	0,x
	cmpd	1,x
	cmpd	-1,x
	cmpd	15,x
	cmpd	-16,x
	cmpd	16,x
	cmpd	-17,x
	cmpd	127,x
	cmpd	-128,x
	cmpd	$0080,x
	cmpd	-$0081,x
	cmpd	a,x
	cmpd	b,x
	cmpd	d,x
	cmpd	,x+
	cmpd	,x++
	cmpd	,-x
	cmpd	,--x
	cmpd	[$1234]
	cmpd	[,x]
	cmpd	[,x]
	cmpd	[15,x]
	cmpd	[127,x]
	cmpd	[$0080,x]
	cmpd	[a,x]
	cmpd	[b,x]
	cmpd	[d,x]
	cmpd	[,x++]
	cmpd	[,--x]
	cmpd	[D0583,pcr]
	cmpd	[D06D6,pcr]
	cmpd	[D075A,pcr]
	cmpd	[D0962,pcr]
	cmpd	,s
	cmpd	,u
	cmpd	,x
	cmpd	,y
D075A:					;				[075A]
	cmps	#$4321
	cmps	#$0013
	cmps	<$12
	cmps	P1234			;				[1234]
	cmps	,x
	cmps	0,x
	cmps	1,x
	cmps	-1,x
	cmps	15,x
	cmps	-16,x
	cmps	16,x
	cmps	-17,x
	cmps	127,x
	cmps	-128,x
	cmps	$0080,x
	cmps	-$0081,x
	cmps	a,x
	cmps	b,x
	cmps	d,x
	cmps	,x+
	cmps	,x++
	cmps	,-x
	cmps	,--x
	cmps	[$1234]
	cmps	[,x]
	cmps	[,x]
	cmps	[15,x]
	cmps	[127,x]
	cmps	[$0080,x]
	cmps	[a,x]
	cmps	[b,x]
	cmps	[d,x]
	cmps	[,x++]
	cmps	[,--x]
	cmps	[D0583,pcr]
	cmps	,s
	cmps	,u
	cmps	,x
	cmps	,y
	cmpu	#$5678
	cmpu	#$0013
	cmpu	<$12
	cmpu	P1234			;				[1234]
	cmpu	,x
	cmpu	0,x
	cmpu	1,x
	cmpu	-1,x
	cmpu	15,x
	cmpu	-16,x
	cmpu	16,x
	cmpu	-17,x
	cmpu	127,x
	cmpu	-128,x
	cmpu	$0080,x
	cmpu	-$0081,x
	cmpu	a,x
	cmpu	b,x
	cmpu	d,x
	cmpu	,x+
	cmpu	,x++
	cmpu	,-x
	cmpu	,--x
	cmpu	[$1234]
	cmpu	[,x]
	cmpu	[,x]
	cmpu	[15,x]
	cmpu	[127,x]
	cmpu	[$0080,x]
	cmpu	[a,x]
	cmpu	[b,x]
	cmpu	[d,x]
	cmpu	[,x++]
	cmpu	[,--x]
	cmpu	[D0583,pcr]
	cmpu	,s
	cmpu	,u
	cmpu	,x
	cmpu	,y
	cmpx	#$ABCD
	cmpx	#$0013
	cmpx	<$12
	cmpx	P1234			;				[1234]
	cmpx	,x
	cmpx	0,x
	cmpx	1,x
	cmpx	-1,x
	cmpx	15,x
	cmpx	-16,x
	cmpx	16,x
	cmpx	-17,x
	cmpx	127,x
	cmpx	-128,x
	cmpx	$0080,x
	cmpx	-$0081,x
	cmpx	a,x
	cmpx	b,x
	cmpx	d,x
	cmpx	,x+
	cmpx	,x++
	cmpx	,-x
	cmpx	,--x
	cmpx	[$1234]
	cmpx	[,s]
	cmpx	[,u]
	cmpx	[,x]
	cmpx	[,y]
	cmpx	[,x]
	cmpx	[15,x]
	cmpx	[127,x]
	cmpx	[$0080,x]
	cmpx	[a,x]
	cmpx	[b,x]
	cmpx	[d,x]
	cmpx	[,x++]
	cmpx	[,--x]
	cmpx	[D0583,pcr]
	cmpx	,s
	cmpx	,u
	cmpx	,x
	cmpx	,y
	cmpy	#$4321
	cmpy	#$0013
	cmpy	<$12
	cmpy	P1234			;				[1234]
	cmpy	,x
	cmpy	0,x
A08E6:					;				[08E6]
	cmpy	1,x
	cmpy	-1,x
	cmpy	15,x
	cmpy	-16,x
	cmpy	16,x
	cmpy	-17,x
	cmpy	127,x
	cmpy	-128,x
	cmpy	$0080,x
	cmpy	-$0081,x
	cmpy	a,x
	cmpy	b,x
	cmpy	d,x
	cmpy	,x+
	cmpy	,x++
	cmpy	,-x
	cmpy	,--x
	cmpy	[$1234]
	cmpy	[,s]
	cmpy	[,u]
	cmpy	[,x]
	cmpy	[,y]
	cmpy	[,x]
	cmpy	[15,x]
	cmpy	[127,x]
	cmpy	[$0080,x]
	cmpy	[a,x]
	cmpy	[b,x]
	cmpy	[d,x]
	cmpy	[,x++]
	cmpy	[,--x]
	cmpy	[D0583,pcr]
	cmpy	,s
	cmpy	,u
	cmpy	,x
	cmpy	,y
D0962:					;				[0962]
	com	<$03
	coma
	comb
	cmpx	<$34
	cwai    $34
	daa
	dec	<$12
	dec	P1234			;				[1234]
	dec	,x
	dec	0,x
	dec	1,x
	dec	-1,x
	dec	15,x
	dec	-16,x
	dec	16,x
	dec	-17,x
	dec	127,x
	dec	-128,x
	dec	$0080,x
	dec	-$0081,x
	dec	a,x
	dec	b,x
	dec	d,x
	dec	,x+
	dec	,x++
	dec	,-x
	dec	,--x
	dec	[$1234]
	dec	[,s]
	dec	[,u]
	dec	[,x]
	dec	[,y]
	dec	[,x]
	dec	[15,x]
	dec	[127,x]
	dec	[$0080,x]
	dec	[a,x]
	dec	[b,x]
	dec	[d,x]
	dec	[,x++]
	dec	[,--x]
	dec	[D0583,pcr]
	dec	,s
	dec	,u
	dec	,x
	dec	,y
	deca
	decb
	leas	-1,s
	leax	-1,x
	eora	#$13
	eora	<$12
	eora	P1234			;				[1234]
	eora	,x
	eora	0,x
	eora	1,x
	eora	-1,x
	eora	15,x
	eora	-16,x
	eora	16,x
	eora	-17,x
	eora	127,x
	eora	-128,x
	eora	$0080,x
	eora	-$0081,x
	eora	a,x
	eora	b,x
	eora	d,x
	eora	,x+
	eora	,x++
	eora	,-x
	eora	,--x
	eora	[$1234]
	eora	[,x]
	eora	[,x]
	eora	[15,x]
	eora	[127,x]
	eora	[$0080,x]
	eora	[a,x]
	eora	[b,x]
	eora	[d,x]
	eora	[,s++]
	eora	[,u++]
	eora	[,x++]
	eora	[,y++]
	eora	[,--s]
	eora	[,--u]
	eora	[,--x]
	eora	[,--y]
	eora	[D0583,pcr]
	eora	,s
	eora	,u
	eora	,x
	eora	,y
	eorb	#$13
	eorb	<$12
	eorb	P1234			;				[1234]
	eorb	,x
	eorb	0,x
	eorb	1,x
	eorb	-1,x
	eorb	15,x
	eorb	-16,x
	eorb	16,x
	eorb	-17,x
	eorb	127,x
	eorb	-128,x
	eorb	$0080,x
	eorb	-$0081,x
	eorb	a,x
	eorb	b,x
	eorb	d,x
	eorb	,x+
	eorb	,x++
	eorb	,-x
	eorb	,--x
	eorb	[$1234]
	eorb	[,x]
	eorb	[,x]
	eorb	[15,x]
	eorb	[127,x]
	eorb	[$0080,x]
	eorb	[a,x]
	eorb	[b,x]
	eorb	[d,x]
	eorb	[,s++]
	eorb	[,u++]
	eorb	[,x++]
	eorb	[,y++]
	eorb	[,--s]
	eorb	[,--u]
	eorb	[,--x]
	eorb	[,--y]
	eorb	[D0583,pcr]
	eorb	,s
	eorb	,u
	eorb	,x
	eorb	,y
	exg	d,x
	exg	y,u
	exg	s,pc
	exg	a,b
	exg	ccr,dpr
	inc	<$12
	inc	P1234			;				[1234]
	inc	,x
	inc	0,x
	inc	1,x
	inc	-1,x
	inc	15,x
	inc	-16,x
	inc	16,x
	inc	-17,x
	inc	127,x
	inc	-128,x
	inc	$0080,x
	inc	-$0081,x
	inc	a,x
	inc	b,x
	inc	d,x
	inc	,x+
	inc	,x++
	inc	,-x
	inc	,--x
	inc	[$1234]
	inc	[,s]
	inc	[,u]
	inc	[,x]
	inc	[,y]
	inc	[,x]
	inc	[15,x]
	inc	[127,x]
	inc	[$0080,x]
	inc	[a,x]
	inc	[b,x]
	inc	[d,x]
	inc	[,s++]
	inc	[,u++]
	inc	[,x++]
	inc	[,y++]
	inc	[,--s]
	inc	[,--u]
	inc	[,--x]
	inc	[,--y]
	inc	[D0583,pcr]
	inc	,s
	inc	,u
	inc	,x
	inc	,y
	inca
	incb
	leas	1,s
	leas	1,s
	leau	1,u
	leax	1,x
	leax	1,x
	leay	1,y
	bne	A0B2C			;				[0B2C]

	jmp	<$12

 
A0B2C:					;				[0B2C]
	bne	A0B31			;				[0B31]

	jmp	P1234			;				[1234]

A0B31:					;				[0B31]
	bne	A0B35			;				[0B35]

	jmp	,x

 
A0B35:					;				[0B35]
	bne	A0B39			;				[0B39]

	jmp	0,x

 
A0B39:					;				[0B39]
	bne	A0B3D			;				[0B3D]

	jmp	1,x

 
A0B3D:					;				[0B3D]
	bne	A0B41			;				[0B41]

	jmp	-1,x

 
A0B41:					;				[0B41]
	bne	A0B45			;				[0B45]

	jmp	15,x

 
A0B45:					;				[0B45]
	bne	A0B49			;				[0B49]

	jmp	-16,x

 
A0B49:					;				[0B49]
	bne	A0B4E			;				[0B4E]

	jmp	16,x

 
A0B4E:					;				[0B4E]
	bne	A0B53			;				[0B53]

	jmp	-17,x

 
A0B53:					;				[0B53]
	bne	A0B58			;				[0B58]

	jmp	127,x

 
A0B58:					;				[0B58]
	bne	A0B5D			;				[0B5D]

	jmp	-128,x

 
A0B5D:					;				[0B5D]
	bne	A0B63			;				[0B63]

	jmp	$0080,x

 
A0B63:					;				[0B63]
	bne	A0B69			;				[0B69]

	jmp	-$0081,x

 
A0B69:					;				[0B69]
	bne	A0B6D			;				[0B6D]

	jmp	a,x

 
A0B6D:					;				[0B6D]
	bne	A0B71			;				[0B71]

	jmp	b,x

 
A0B71:					;				[0B71]
	bne	A0B75			;				[0B75]

	jmp	d,x

 
A0B75:					;				[0B75]
	bne	A0B79			;				[0B79]

	jmp	,x+

 
A0B79:					;				[0B79]
	bne	A0B7D			;				[0B7D]

	jmp	,x++

 
A0B7D:					;				[0B7D]
	bne	A0B81			;				[0B81]

	jmp	,-x

 
A0B81:					;				[0B81]
	bne	A0B85			;				[0B85]

	jmp	,--x

 
A0B85:					;				[0B85]
	bne	A0B8B			;				[0B8B]

	jmp	[$1234]

 
A0B8B:					;				[0B8B]
	bne	A0B8F			;				[0B8F]

	jmp	[,s]

 
A0B8F:					;				[0B8F]
	bne	A0B93			;				[0B93]

	jmp	[,u]

 
A0B93:					;				[0B93]
	bne	A0B97			;				[0B97]

	jmp	[,x]

 
A0B97:					;				[0B97]
	bne	A0B9B			;				[0B9B]

	jmp	[,y]

 
A0B9B:					;				[0B9B]
	bne	A0B9F			;				[0B9F]

	jmp	[,x]

 
A0B9F:					;				[0B9F]
	bne	A0BA4			;				[0BA4]

	jmp	[15,x]

 
A0BA4:					;				[0BA4]
	bne	A0BA9			;				[0BA9]

	jmp	[127,x]

 
A0BA9:					;				[0BA9]
	bne	A0BAF			;				[0BAF]

	jmp	[$0080,x]

 
A0BAF:					;				[0BAF]
	bne	A0BB3			;				[0BB3]

	jmp	[a,x]

 
A0BB3:					;				[0BB3]
	bne	A0BB7			;				[0BB7]

	jmp	[b,x]

 
A0BB7:					;				[0BB7]
	bne	A0BBB			;				[0BBB]

	jmp	[d,x]

 
A0BBB:					;				[0BBB]
	bne	A0BBF			;				[0BBF]

	jmp	[,s++]

 
A0BBF:					;				[0BBF]
	bne	A0BC3			;				[0BC3]

	jmp	[,u++]

 
A0BC3:					;				[0BC3]
	bne	A0BC7			;				[0BC7]

	jmp	[,x++]

 
A0BC7:					;				[0BC7]
	bne	A0BCB			;				[0BCB]

	jmp	[,y++]

 
A0BCB:					;				[0BCB]
	bne	A0BCF			;				[0BCF]

	jmp	[,--s]

 
A0BCF:					;				[0BCF]
	bne	A0BD3			;				[0BD3]

	jmp	[,--u]

 
A0BD3:					;				[0BD3]
	bne	A0BD7			;				[0BD7]

	jmp	[,--x]

 
A0BD7:					;				[0BD7]
	bne	A0BDB			;				[0BDB]

	jmp	[,--y]

 
A0BDB:					;				[0BDB]
	bne	A0BE1			;				[0BE1]

	jmp	[D0583,pcr]

 
A0BE1:					;				[0BE1]
	bne	A0BE5			;				[0BE5]

	jmp	,s

 
A0BE5:					;				[0BE5]
	bne	A0BE9			;				[0BE9]

	jmp	,u

 
A0BE9:					;				[0BE9]
	bne	A0BED			;				[0BED]

	jmp	,x

 
A0BED:					;				[0BED]
	bne	A0BF1			;				[0BF1]

	jmp	,y

 
A0BF1:					;				[0BF1]
	jsr	<$12

	jsr	P1234			;				[1234]

	jsr	,x

 
S0BF7:
        FCB     $84, $AD, $00, $AD, $01, $AD, $1F, $AD	; ........  $0BF7
        FCB     $0F, $AD, $10, $AD, $88, $10, $AD, $88	; ........  $0BFF
        FCB     $EF, $AD, $88, $7F, $AD, $88, $80, $AD	; ........  $0C07
        FCB     $89, $00, $80, $AD, $89, $FF, $7F, $AD	; ........  $0C0F
        FCB     $86, $AD, $85, $AD, $8B, $AD, $80, $AD	; ........  $0C17
        FCB     $81, $AD, $82, $AD, $83, $AD, $9F, $12	; ........  $0C1F
        FCB     $34, $AD, $F4, $AD, $D4, $AD, $94, $AD	; 4.......  $0C27
        FCB     $B4, $AD, $94, $AD, $98, $0F, $AD, $98	; ........  $0C2F
        FCB     $7F, $AD, $99, $00, $80, $AD, $96, $AD	; ........  $0C37
        FCB     $95, $AD, $9B, $AD, $F1, $AD, $D1, $AD	; ........  $0C3F
        FCB     $91, $AD, $B1, $AD, $F3, $AD, $D3, $AD	; ........  $0C47
        FCB     $93, $AD, $B3, $AD, $9D, $F9, $2D, $AD	; ......-.  $0C4F
        FCB     $E4, $AD, $C4, $AD, $84, $AD, $A4, $10	; ........  $0C57
        FCB     $24, $F8, $45, $10, $25, $01, $AA, $10	; $.E.%...  $0C5F
        FCB     $27, $F8, $3D, $10, $2C, $01, $A2, $10	; '.=.,...  $0C67
        FCB     $2E, $F8, $35, $10, $22, $01, $9A, $10	; ..5."...  $0C6F
        FCB     $24, $F8, $2D, $10, $2F, $01, $92, $10	; $.-./...  $0C77
        FCB     $25, $F8, $25, $10, $23, $01, $8A, $10	; %.%.#...  $0C7F
        FCB     $2D, $F8, $1D, $10, $2B, $01, $82, $10	; -...+...  $0C87
        FCB     $26, $F8, $15, $10, $2A, $01, $7A, $16	; &...*.z.  $0C8F
        FCB     $F8, $0E, $10, $21, $01, $73, $17, $F8	; ...!.s..  $0C97
        FCB     $07, $10, $28, $01, $6C, $10, $29, $F7	; ..(.l.).  $0C9F
        FCB     $FF, $86, $01, $86, $01, $C6, $02, $C6	; ........  $0CA7
        FCB     $02, $CC, $98, $76, $10, $CE, $12, $34	; ...v...4  $0CAF
        FCB     $CE, $23, $45, $8E, $34, $56, $10, $8E	; .#E.4V..  $0CB7
        FCB     $45, $67, $32, $9F, $12, $34, $32, $7F	; Eg2..42.  $0CBF
        FCB     $32, $61, $33, $F4, $33, $5F, $33, $41	; 2a3.33A  $0CC7
        FCB     $30, $A4, $30, $1F, $30, $01, $31, $84	; 0.0.0.1.  $0CCF
        FCB     $31, $3F, $31, $21, $08, $13, $48, $58	; 1?1!..HX  $0CD7
        FCB     $64, $9F, $43, $21, $44, $54, $44, $56	; d.C!DTDV  $0CDF
        FCB     $3D, $00, $34, $70, $56, $78, $60, $9F	; =.4pVx`.  $0CE7
        FCB     $AB, $CD, $60, $99, $AB, $CD, $40, $50	; ..`...@P  $0CEF
        FCB     $12, $8A, $13, $9A, $12, $BA, $12, $34	; .......4  $0CF7
        FCB     $AA, $84, $AA, $00, $AA, $01, $AA, $1F	; ........  $0CFF
        FCB     $AA, $0F, $AA, $10, $AA, $88, $10, $AA	; ........  $0D07
        FCB     $88, $EF, $AA, $88, $7F, $AA, $88, $80	; ........  $0D0F
        FCB     $AA, $89, $00, $80, $AA, $89, $FF, $7F	; ........  $0D17
        FCB     $AA, $86, $AA, $85, $AA, $8B, $AA, $80	; ........  $0D1F
        FCB     $AA, $81, $AA, $82, $AA, $83, $AA, $9F	; ........  $0D27
        FCB     $12, $34, $AA, $94, $AA, $94, $AA, $98	; .4......  $0D2F
        FCB     $0F, $AA, $98, $7F, $AA, $99, $00, $80	; ........  $0D37
        FCB     $AA, $96, $AA, $95, $AA, $9B, $AA, $F1	; ........  $0D3F
        FCB     $AA, $D1, $AA, $91, $AA, $B1, $AA, $F3	; ........  $0D47
        FCB     $AA, $D3, $AA, $93, $AA, $B3, $AA, $9D	; ........  $0D4F
        FCB     $F2, $A7, $AA, $9D, $F3, $76, $AA, $9D	; .....v..  $0D57
        FCB     $F3, $AE, $AA, $9D, $F8, $1E, $AA, $E4	; ........  $0D5F
        FCB     $AA, $C4, $AA, $84, $AA, $A4, $CA, $13	; ........  $0D67
        FCB     $DA, $12, $FA, $12, $34, $EA, $84, $EA	; ....4...  $0D6F
        FCB     $00, $EA, $01, $EA, $1F, $EA, $0F, $EA	; ........  $0D77
        FCB     $10, $EA, $88, $10, $EA, $88, $EF, $EA	; ........  $0D7F
        FCB     $88, $7F, $EA, $88, $80, $EA, $89, $00	; ........  $0D87
        FCB     $80, $EA, $89, $FF, $7F, $EA, $86, $EA	; ........  $0D8F
        FCB     $85, $EA, $8B, $EA, $80, $EA, $81, $EA	; ........  $0D97
        FCB     $82, $EA, $83, $EA, $9F, $12, $34, $EA	; ......4.  $0D9F
        FCB     $94, $EA, $94, $EA, $98, $0F, $EA, $98	; ........  $0DA7
        FCB     $7F, $EA, $99, $00, $80, $EA, $96, $EA	; ........  $0DAF
        FCB     $95, $EA, $9B, $EA, $F1, $EA, $D1, $EA	; ........  $0DB7
        FCB     $91, $EA, $B1, $EA, $F3, $EA, $D3, $EA	; ........  $0DBF
        FCB     $93, $EA, $B3, $EA, $9D, $F2, $32, $EA	; ......2.  $0DC7
        FCB     $9D, $F3, $01, $EA, $9D, $F3, $39, $EA	; ......9.  $0DCF
        FCB     $9D, $F7, $A9, $EA, $E4, $EA, $C4, $EA	; ........  $0DD7
        FCB     $84, $EA, $A4, $1A, $74, $1A, $55, $1A	; ....t.U.  $0DDF
        FCB     $AA, $1A, $05, $9A, $13, $EA, $E4, $34	; .......4  $0DE7
        FCB     $02, $34, $04, $34, $04, $34, $D1, $36	; .4.4.4.6  $0DEF
        FCB     $4E, $34, $10, $35, $02, $35, $04, $35	; N4.5.5.5  $0DF7
        FCB     $26, $37, $16, $35, $10, $09, $34, $49	; &7.5..4I  $0DFF
        FCB     $59, $76, $67, $89, $46, $56, $26, $01	; Yvg.FV&.  $0E07
        FCB     $3B, $26, $01, $39			; ;&.9  $0E0F
D0E13:					;				[0E13]
        FCB     $34, $04, $A0, $E0, $B2, $12, $34, $A2	; 4.....4.  $0E13
        FCB     $84, $E2, $C4, $1A, $01, $1A, $10, $1A	; ........  $0E1B
        FCB     $02, $1D, $A7, $C0, $A7, $C0, $E7, $C2	; ........  $0E23
        FCB     $E7, $C2, $DD, $13, $10, $EF, $D4, $EF	; ........  $0E2B
        FCB     $F4, $AF, $B4, $10, $AF, $94, $B0, $12	; ........  $0E33
        FCB     $34, $A0, $88, $17, $C0, $38, $83, $00	; 4....8..  $0E3B
        FCB     $01, $3F, $10, $3F, $11, $3F, $13, $1F	; .?.?.?..  $0E43
        FCB     $89, $1F, $8A, $1F, $98, $1F, $98, $1F	; ........  $0E4B
        FCB     $A8, $0D, $23, $4D, $5D, $1F, $41, $1F	; ..#M].A.  $0E53
        FCB     $14, $3C, $6D, $89, $04, $A7, $6D, $99	; .<m...m.  $0E5B
        FCB     $04, $A7				; ..  $0E63
 
        END                                        ; End of part to assemble
 
 
